config/routes.rb
Canalweb::Application.routes.draw do

  devise_for :users

  get "amigos/index"

  get "favorito/index"

  get "canals/buscar"

  resources :canals

  get "user_profile/edit"

  get "user_profile/show"

  get "home/index"

  resources :user_profiles

  root :to => 'home#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/canal.rb
class Canal < ActiveRecord::Base
  belongs_to :user_profile
  has_many :favoritos
end

app/controllers/canals_controller.rb
class CanalsController < ApplicationController
  # GET /canals
  # GET /canals.json
  def index
    @title = "Meus Canais"
    @canals = Canal.find(:all, :conditions => ["user_id = ?", current_user.id])
    #@canals = Canal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @canals }
    end
  end

  def buscar
    @title = "Procurar Canal"
    if params[:texto] != nil
      @canals = Canal.all(:conditions => ["nome like ? or descricao like ?", "%#{params[:texto]}%", "%#{params[:texto]}%"])
    end
  end

  # GET /canals/1
  # GET /canals/1.json
  def show
    @title = "Pagina do canal"
    @canal = Canal.find(params[:id])

    @favoritos = Favorito.all(:conditions => ["user_profile_id = ? and canal_id = ?", current_user.user_profile.id, @canal.id])
    @favorito = nil
    @favoritos.each do |f|
      @favorito = f
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @canal }
    end
  end

  # GET /canals/new
  # GET /canals/new.json
  def new
    @title = "Criar Canal"
    @canal = Canal.new
    @canal.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @canal }
    end
  end

  # GET /canals/1/edit
  def edit
    @title = "Editar Canal"
    @canal = Canal.find(params[:id])
  end

  # POST /canals
  # POST /canals.json
  def create
    @canal = Canal.new(params[:canal])
    @canal.user_id = current_user.id

    respond_to do |format|
      if @canal.save
        format.html { redirect_to @canal, notice: 'Canal was successfully created.' }
        format.json { render json: @canal, status: :created, location: @canal }
      else
        format.html { render action: "new" }
        format.json { render json: @canal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /canals/1
  # PUT /canals/1.json
  def update
    @canal = Canal.find(params[:id])
    @canal.user_id = current_user.id

    respond_to do |format|
      if @canal.update_attributes(params[:canal])
        format.html { redirect_to @canal, notice: 'Canal was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @canal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /canals/1
  # DELETE /canals/1.json
  def destroy
    @canal = Canal.find(params[:id])
    @canal.destroy

    respond_to do |format|
      format.html { redirect_to canals_url }
      format.json { head :ok }
    end
  end

end

app/helpers/canals_helper.rb
module CanalsHelper
end

app/views/canals/_form.html.erb
<%= form_for(@canal) do |f| %>
  <% if @canal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canal.errors.count, "error") %> prohibited this canal from being saved:</h2>

      <ul>
      <% @canal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :tipo_programacao %><br />
    <%= f.text_field :tipo_programacao %>
  </div>
  <div class="field">
    <%= f.label :idade_minima %><br />
    <%= f.number_field :idade_minima %>
  </div>
  <div class="field">
    <%= f.label :imagem %><br />
    <%= f.text_field :imagem %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit "Salvar" %>
  </div>
<% end %>

app/views/canals/buscar.html.erb
<%= form_tag() do %>
  <div class="form_row">
    <label for="texto">Buscar por:</label>
    <%= text_field_tag "texto", params[:texto]%>
    <input type="submit" value="buscar" />
  </div>
<% end %>

</br>

<% if @canals and not @canals.empty? %>
  <table class="canals" border="0" cellpadding="5" cellspacing="1">
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
    </tr>
    <% @canals.each do |canal| %>
      <tr>
        <td><%= link_to canal.nome, :controller => "/canals", :action => "show", :id => canal.id %> </td>
        <td><%= canal.descricao %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/canals/edit.html.erb
<%= render 'form' %>

<%= link_to 'Mostrar', @canal %> |
<%= link_to 'Voltar', canals_path %>

app/views/canals/index.html.erb
<table>
  <tr>
    <th>Nome</th>
    <th>Tipo programacao</th>
    <th>Idade minima</th>
    <th>Imagem</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @canals.each do |canal| %>
  <tr>
    <td><%= canal.nome %></td>
    <td><%= canal.tipo_programacao %></td>
    <td><%= canal.idade_minima %></td>
    <td><%= canal.imagem %></td>
    <td><%= canal.descricao %></td>
    <td><%= link_to 'Mostrar', canal %></td>
    <td><%= link_to 'Editar', edit_canal_path(canal) %></td>
    <td><%= link_to 'excluir', canal, confirm: 'tem certeza?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Criar Canal', new_canal_path %>

app/views/canals/new.html.erb
<%= render 'form' %>

<%= link_to 'Voltar', canals_path %>

app/views/canals/show.html.erb
<p id="notice"><%= notice %></p>
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0" width="400" height="400">
  <param name="src" value="/swf/canalweb.swf" />
  <embed src="/swf/canalweb.swf" FlashVars="id=<%=current_user.user_profile.id%>&canal=<%= @canal.id%>&code=<%=@canal.user_id %>" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" width="640" height="480"></embed>
</object>
</br>
<p>
  <b>Nome:</b>
  <%= @canal.nome %>
</p>

<p>
  <b>Tipo programacao:</b>
  <%= @canal.tipo_programacao %>
</p>

<p>
  <b>Idade minima:</b>
  <%= @canal.idade_minima %>
</p>

<p>
  <b>Imagem:</b>
  <%= @canal.imagem %>
</p>

<p>
  <b>Descricao:</b>
  <%= @canal.descricao %>
</p>

<% if @canal.user_id != current_user.user_profile.id %>
  <% if @favorito != nil %>
    <%= link_to 'Remover Favorito', :controller => "/favorito", :action => "deletar", :favorito_id => @favorito  %> |
  <% else %>
    <%= link_to 'Adicionar Favorito', :controller => "/favorito", :action => "adicionar", :canal_id => @canal.id %> |
  <% end %>

<% end %>
<%= link_to 'Voltar', canals_path %>